baseURL = "https://kuoted.vercel.app/"
theme = "hugo-bearblog"
title = "Kuoted"
author = "Daniel Kuo"
languageCode = "en-US"
enableRobotsTXT = true

disableKinds = ["taxonomy"]
ignoreErrors = ["error-disable-taxonomy"]

[permalinks]
  blog = "/:slug/"
  tags = "/blog/:slug"

[params]
  description = "Notes and quotes"
  favicon = ""
  enablePostNavigator = true
  dateFormat = "2006-01-02"

[markup]
  [markup.highlight]
    style = "friendly"
    lineNos = true
    lineNumbersInTable = false
    codeFences = true
  [markup.goldmark.renderer]
    unsafe = true
